### ISSUE TITLE
Lingering references to 3.5.0 and 301

### ISSUE THREAD

**Issue by adamlwgriffiths** [electronstudio/raylib-python-cffi#33]
Looks like 3.7.0 changes were merged with commit 124f0c77a98c1d8395ed443b37cd0e165ea9965e.
But there are a number of references to 3.5 still in the repo:

https://github.com/electronstudio/raylib-python-cffi/blob/master/raylib/dynamic/__init__.py#L9-L10

(Note: this one mentions 3.5.0 _and_ 301)

https://github.com/electronstudio/raylib-python-cffi/blame/master/README.md#L75

**Comment by electronstudio** [comment]
This is an issue with Raylib.  They failed to update the file names to 3.7.  So when you install Raylib 3.7 you get files with names like /usr/local/lib/libraylib.so.3.5.0.

The file name in the README could be updated but it's never going to exactly match what the end user has anyway, because different systems will produce different file names.  it's just an example.

**Comment by electronstudio** [comment]
Since Raylib itself doesn't remember to update these names, and since it's annoying for us to remember, maybe we should just remove the version numbers?

Currently on my system I have raylib 3.7 installed and the file names are: libraylib.so, libraylib.so.351, libraylib.so.3.5.0

The first two are sym links.  So with your patch it will search for:

['libraylib.so.3.7.0','libraylib.so.3', 'libraylib.so']

The first two will fail and then it will succeed with the third.  So maybe we just remove the first two?

**Comment by adamlwgriffiths** [comment]
I think we could. I just wasn't sure I could speak for all distros.

As you say, the 3.7.0 tag has the incorrect version specified and the resulting binary is listed as 3.5.0.
In my Nix package I incorporated [this commit](https://github.com/raysan5/raylib/commit/204aa4c46fdd6986aa0130eeba658562c540759f.patch) which fixes this.
This was merged as part of [this PR](https://github.com/raysan5/raylib/pull/1761).
So Nix has the proper filename for raylib 3.7.0.

```
lrwxrwxrwx 1 root root      16 Jan  1  1970 libraylib.so -> libraylib.so.370
-r-xr-xr-x 1 root root 1534000 Jan  1  1970 libraylib.so.3.7.0
lrwxrwxrwx 1 root root      18 Jan  1  1970 libraylib.so.370 -> libraylib.so.3.7.0
```

Perhaps `libraylib.so` + env var is enough.

FYI, I addressed these issues in this PR: https://github.com/electronstudio/raylib-python-cffi/pull/34

**Comment by electronstudio** [comment]
Raylib really needs a stable branch.

I'm happy to merge your PR I just wasn't sure if you want to change anything else.

Previously I was shipping one single wheel file that contained static libraries and dynamic libraries (in "raylib/dynamic") for all platforms. However this isn't how Pypi is supposed to work - there is supposed to be one wheel per platform.  Then if it can't find one for your platform is automatically builds it from source.

So for the 3.7 release I switched to multiple wheels, each containing the static libs for one platform and no dynamic libs at all.

I think ideally the dynamic version should be a totally separate library, because it doesn't require building and does work on any platform that user supplies libs for.  However I haven't done this because I don't find the dynamic version to be as good so I don't use it myself or really want to encourage other people to use it.

**Comment by adamlwgriffiths** [comment]
Lets move the conversation over to the PR
