### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/raylib-python-cffi#47]
We should split the examples into ones that use the C API and ones that use the Python API.

We should add more examples.

We should test all the examples work, with both the static and dynamic binding.

**Comment by JackWitherell** [comment]
Shader examples that change uniforms
shaders_fog.py
shaders_texture_drawing.py
shaders_texture_waves.py
don't work due to the change of `rl.UNIFORM_FLOAT` being changed to `rl.SHADER_UNIFORM_FLOAT` in an earlier version. Otherwise they work fine.

**Comment by romariops** [comment]
Are there contribution rules as a naming pattern for branches?

**Comment by SirNate0** [comment]
An example showing how to create a mesh in python code would be helpful. I don't whether there is one in normal raylib (as functions generating meshes in rmodels.c are already examples), but in Python it took me many hours to figure out (and required building a debug build of the library so I could figure out why I was getting all the SegFaults).

If you want, feel free to use my Gist [here](https://gist.github.com/SirNate0/0819112af5eff7b207af136d427a25f5), based on the GenMeshCube code (though it does use numpy to handle the mesh data arrays, rather than attempting a more manual conversion).

**Comment by electronstudio** [comment]
Thanks.  I will add some code to pyray to make it do the` ffi.from_buffer` calls automatically when a buffer is used as an argument to a struct creator method (e.g. here `Mesh()`).  I will also change your example to use` array.array` instead of `numpy.ndarray`.

It would be nice if we could send Python lists to the struct creator and also if it didnt require maintaining references to the buffers to prevent garbage collection, but I cant see any easy way of doing that automatically.  I guess we'd need Mesh() to return a proxy object that contains both the cdata struct and the references.

**Comment by electronstudio** [comment]
According to CFFI docs, a `global_weakkeydict = weakref.WeakKeyDictionary()` can be used to keep the references alive automatically.  Unfortunately it's difficult to test if it's working correctly because errors caused by GC seem to be non-deterministic - I sometimes see them, but I can't force them to occur repeatably, so I don't know if they are all gone.

**Comment by electronstudio** [comment]
https://github.com/electronstudio/raylib-python-cffi/pull/119

**Comment by electronstudio** [comment]
https://github.com/electronstudio/raylib-python-cffi/issues/155
