### ISSUE TITLE
pyray.set_shader_value doesn't work

### ISSUE THREAD

**Issue by JackWitherell** [electronstudio/raylib-python-cffi#57]
Setting the uniform of a shader doesn't work in pyray as early as 4.0.0.2, still fails in 4.0.0.3
Platform - Windows (this issue is likely platform independent)

Issue - Following the example causes an error
`TypeError: expected a cdata struct/union/array object`
Example:
```py
import pyray as pr

pr.init_window(1280, 720, "any")

shader = pr.load_shader(b"", b"shader.fs")
time = pr.ffi.new("float *", 0.0)
timeLoc = pr.get_shader_location(shader, b"uTime")
pr.set_shader_value(shader, timeLoc, time, pr.SHADER_UNIFORM_FLOAT) # <<failure on this line
```

**Comment by electronstudio** [comment]
the issue is we added auto pointerization to pyray, so if the C function takes a pointer the python argument gets automatically turned into a pointer.  in this case it's *already* a pointer, so we shouldn't do pointerization.

i guess i will have to add a special case for when it's already a pointer.  Ideally python programmers wouldn't have to use ffi.new and would just supply a python float, but I don't know how that could be done automatically.

**Comment by JackWitherell** [comment]
Good call, but changing that float pointer to a float causes it to fail as well.

![image](https://user-images.githubusercontent.com/4626546/152220745-81f0fd8a-55a2-4724-9844-08d50b62b3e2.png)

**Comment by electronstudio** [comment]
Yeah, problem is we can't pointerize a *python* float, it's not the same thing as a *C* float.

You can mix raylib/pyray code in same program to get round this until it's fixed.

**Comment by electronstudio** [comment]
Please update to raylib-4.0.0.4 and test.  *Both* of your examples, the one with the float* and the one with 0.0 should now work.
